language: node_js

node_js:
- stable
- '6'
- '4'

cache:
  directories:
    - node_modules

# after_success:
#   - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master

before_script:
  - "npm i -g gatsby"
  - "npm i"

script:
  - "npm run test"

after_success:
  - "npm run deploy"